name: run_daily

on:
  # run at 7am every morning
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: selenium/standalone-chrome
    steps:
      - uses: actions/checkout@v2
      - name: Install and run
        run: |
          cd wordle_solver && pip install -e .
          wordle solve --headless
